### PR TITLE
Adds the template to connect to Glue [sc-44082]

### PR DESCRIPTION
**Pull request by verdan**
Signed-off-by: Verdan <verdan@getselectstar.com>

## Description

Adds a Cloudformation template to connect to the AWS Glue

## How to reproduce/test?

Installed the stack in the `playground` environment, and used the values to generate the following script

```python
import boto3
from aws_assume_role_lib import aws_assume_role_lib

session = boto3.Session()  # use AWS IAM role via IRSA
assumed_role_session = aws_assume_role_lib.assume_role(
    session,
    RoleArn="arn:aws:iam::792169733636:role/VerdanGlueTesting-CrossAccountRole-D6SHCC5MAWFL",
    ExternalId="Cyugsa3HwdV2Q5pbBEG6LXeVQ6XUBACRXFCG4XmU4fVjoNPW56gJRpjBq7tpSh8a",
)
glue_object = assumed_role_session.client("glue")

print(glue_object.get_databases())

"""
{
    "DatabaseList": [
        {
            "Name": "awsgluecrawler",
            "CreateTime": datetime.datetime(2022, 12, 15, 0, 28, 40, tzinfo=tzlocal()),
            "CreateTableDefaultPermissions": [
                {
                    "Principal": {
                        "DataLakePrincipalIdentifier": "IAM_ALLOWED_PRINCIPALS"
                    },
                    "Permissions": ["ALL"],
                }
            ],
            "CatalogId": "792169733636",
        }
    ],
    "ResponseMetadata": {
        "RequestId": "a5aae4ac-f799-4b59-925e-314c95f8dd39",
        "HTTPStatusCode": 200,
        "HTTPHeaders": {
            "date": "Wed, 08 Feb 2023 16:53:53 GMT",
            "content-type": "application/x-amz-json-1.1",
            "content-length": "256",
            "connection": "keep-alive",
            "x-amzn-requestid": "a5aae4ac-f799-4b59-925e-314c95f8dd39",
        },
        "RetryAttempts": 0,
    },
}
"""

```

## Type of change

-   [ ] Refactor (non-breaking change that improves codebase).
-   [ ] Bug fix (non-breaking change that fixes an issue).
-   [ ] New feature (non-breaking change that adds functionality).
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
-   [ ] Chore (none of the above, but still important)

## Related tickets

-   Story sc-44082

## Checklists

-   [ ] No backend changes needed.
-   [ ] All related backend changes are ready.
    -   [links to related PRs]

### CODE REVIEW

**Comment by ad-m-ss** [comment]
Please:

* update workflow file to enable deployment: https://github.com/selectstar/cloudformation-templates/blob/main/.github/workflows/deploy.yml#L46
* add CONTRIBUTING.md file

Do you plan to have E2E tests? I suggested omitting them at first to focus on the Python code because it's easier to test and understand with simple Python code, but testing E2E with Terraform is valuable in long-term maintenance.

**Comment by verdan** [comment]
> Please:
> 
> * update workflow file to enable deployment: https://github.com/selectstar/cloudformation-templates/blob/main/.github/workflows/deploy.yml#L46
> * add CONTRIBUTING.md file
> 
> Do you plan to have E2E tests? I suggested omitting them at first to focus on the Python code because it's easier to test and understand with simple Python code, but testing E2E with Terraform is valuable in long-term maintenance.

Just wondering, what should be in the contributing.md ?

**Comment by ad-m-ss** [comment]
> Just wondering, what should be in the contributing.md ?

Description about deployment & links: https://github.com/selectstar/cloudformation-templates/blob/main/redshift/CONTRIBUTING.md

**Comment by verdan** [comment]
> > Just wondering, what should be in the contributing.md ?
> 
> Description about deployment & links: https://github.com/selectstar/cloudformation-templates/blob/main/redshift/CONTRIBUTING.md

ah, I thought the repo contributing.md. got it.

**Comment by ad-m-ss** [comment]
> Do you plan to have E2E tests? I suggested omitting them at first to focus on the Python code because it's easier to test and understand with simple Python code, but testing E2E with Terraform is valuable in long-term maintenance.

**Comment by verdan** [comment]
> > Do you plan to have E2E tests? I suggested omitting them at first to focus on the Python code because it's easier to test and understand with simple Python code, but testing E2E with Terraform is valuable in long-term maintenance.

@ad-m-ss I am not going to add the tests at the moment. But will add a ticket in my epic to do it later. 

https://app.shortcut.com/select-star/story/44464/aws-glue-e2e-test-for-aws-glue-cloudformation-template

**Review by ad-m-ss — APPROVED** [review]

**Pull request merged**
